# Generated by Django 4.2.7 on 2026-01-31 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.DecimalField(decimal_places=1, help_text='in inches', max_digits=5)),
                ('waist', models.DecimalField(decimal_places=1, help_text='in inches', max_digits=5)),
                ('hips', models.DecimalField(decimal_places=1, help_text='in inches', max_digits=5)),
                ('shoulder', models.DecimalField(decimal_places=1, help_text='in inches', max_digits=5)),
                ('sleeve_length', models.DecimalField(decimal_places=1, help_text='in inches', max_digits=5)),
                ('full_length', models.DecimalField(decimal_places=1, help_text='in inches', max_digits=5)),
                ('additional_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Measurements',
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_type', models.CharField(choices=[('existing', 'Existing Product'), ('custom', 'Custom Project')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('custom_description', models.TextField(blank=True, help_text='Required for custom project quotes')),
                ('reference_image', models.ImageField(blank=True, help_text='Optional reference image for custom projects', null=True, upload_to='quote_references/')),
                ('fabric_preference', models.CharField(max_length=200)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='clients.client')),
                ('measurements', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quotes.measurements')),
                ('product', models.ForeignKey(blank=True, help_text='Required for existing product quotes', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
